Usage example for readme
hello-seam/seamapi-javascript pull request #4
Opened 2022-01-31 14:50 UTC by andrii-balitskyi

- usage example added to readme
- url added to ConnectWebview type

2022-02-02 01:23 UTC, seveibar requested changes

2022-02-02 01:23 UTC, seveibar commented on README.md
> +    }
it's more conventional to write

```ts
const accessCodeList = seam.accessCodes.list(someLockId)
console.log(accessCodeList)
/*
{
    access_codes: [
      {
        access_code_id: "some-access-code-1",
        name: "Some Access Code",
        code: "1234",
        type: "ongoing",
        created_at: "2022-02-01T12:57:40.843Z",
      },
    ],
  }
*/
```

2022-02-02 01:23 UTC, seveibar commented on README.md
> +// export SEAM_API_KEY=***
```suggestion
// Seam will automatically use the SEAM_API_KEY environment variable if you
// don't provide an api_key to `new Seam()`
```

2022-02-02 16:21 UTC, seveibar approved these changes

2022-02-02 16:27 UTC, codetheweb reviewed
Looks pretty good to me!

2022-02-02 16:27 UTC, codetheweb commented on README.md
> +seam.locks.lockDoor(someLockId)
These API calls should be `await`ed.

2022-02-03 14:49 UTC, codetheweb approved these changes

2022-02-04 10:43 UTC, merged